### PR TITLE
thailand language

### PR DESCRIPTION
**Pull request by mods-hd**

### CODE REVIEW

**Review by Sayrix — CHANGES_REQUESTED** [review]
Can you remove the ✅ emoji in commands.nowplaying.liked (l. 24) please?
Looks good to me, translated into English.

**Comment by mods-hd** [comment]
Done

**Review by Sayrix — APPROVED** [review]
lgtm

**Comment by Sayrix** [comment]
What's your Discord ? Can you join https://discord.gg/qcmE5CMKpV ?

**Comment by mods-hd** [comment]
Sorry for the late reply. I don't get a notification

My discord is modshd

ID: 547231585368539136

**Pull request merged**
